const ActionTypes = {
  GETBY_CITYNAME: "GETBY_CITYNAME",
  ADDCITY_TOMYLIST: "ADDCITY_TOMYLIST",
  DELETECITY_TOMYLIST: "DELETECITY_TOMYLIST",
  GETCITYBYID: "GETCITYBYID",
  FETCH_CITIES: "FETCH_CITIES",
  GETBY_MYLIST: "GETBY_MYLIST",
};
export default ActionTypes;
